---
- name: Test login banner
  hosts: all
  become: True
  collections:
    - jeroenvandelockand.loginmsg
  tasks:
  - name: put a logon message before logging in
    loginmsg:
      text: Hello, you are entering a Hackathon Machine!
      when: before
      fqdn: True
      state: present

  - name: put a logon message after logging in
    loginmsg:
      text: Hi there, welcome in a Hackathon Machine!
      when: after
      fqdn: False
      state: present