---
- name: set up login messages
  hosts: all
  collections:
    - jeroenvandelockand.loginmsg  
  gather_facts: no
  tasks:
  - name: put a logon message before logging in
    loginmsg:
      text: "Hello, you are entering a Hackathon Machine!"
      when: before
      fqdn: true
      state: present