---
- name: Test login banner
  hosts: all
  become: True
  collections:
    - jeroenvandelockand.loginmsg
  tasks:
  - name: Add pre-login banner with fqdn
    loginmsg:
      text: This should go in /etc/issue with fqdn
      when: before
      fqdn: True
      state: present

  - name: Add login banner without fqdn
    loginmsg:
      text: This should go in /etc/motd without fqdn
      when: after
      fqdn: False
      state: present